version: "3"

services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host

    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Berlin

    volumes:
      - ./homebridge:/homebridge

    healthcheck:
      test: curl --fail http://localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

