version: "3"

services:
  scheduler:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - wget-casa-blu-fetch
    container_name: scheduler
    command: daemon --docker
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.fetchpy.schedule: "@every 30m"
      ofelia.job-run.fetchpy.container: "wget-casa-blu-fetch"
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  wget-casa-blu-fetch:
    build:
      context: ../wget/
      dockerfile: Dockerfile
    container_name: wget-casa-blu-fetch
    environment:
      - url=http://casa-blu.de/cgi-bin/fetch.py
      - contentOut=fetch.txt
      - requestLog=fetch.log
    volumes:
      - ../wget/logs:/logs:rw


